import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const game=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));
renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
game.appendChild(renderer.domElement);

const scene=new THREE.Scene();
scene.fog=new THREE.FogExp2(0xb9c1bd,.0068);
scene.add(new THREE.HemisphereLight(0xe2e8e3,0x34372f,1.65));
const sun=new THREE.DirectionalLight(0xffefcf,2.5);sun.position.set(-45,70,-32);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=70;sun.shadow.camera.bottom=-70;scene.add(sun);

const camera=new THREE.PerspectiveCamera(39,innerWidth/innerHeight,.1,240);
const camTarget=new THREE.Vector3(0,0,4);camera.position.set(48,46,60);camera.lookAt(camTarget);
const palette={snow:0xc7cbc5,road:0x6c665b,wood:0x66533d,steel:0x50595a,olive:0x58634b,brick:0x6a5548};
const box=(w,h,d,color,x,y,z)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.92}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m};

const ground=new THREE.Mesh(new THREE.PlaneGeometry(104,96,10,10).rotateX(-Math.PI/2),new THREE.MeshStandardMaterial({color:palette.snow,roughness:1}));ground.receiveShadow=true;scene.add(ground);
const base=new THREE.Mesh(new THREE.BoxGeometry(106,2.2,98),new THREE.MeshStandardMaterial({color:0x4b4a43,roughness:1}));base.position.y=-1.2;base.receiveShadow=true;scene.add(base);
box(8,.08,86,palette.road,-9,.06,0);box(104,.12,7,0x4c4941,0,.08,-28);for(let x=-50;x<=50;x+=2.6)box(.18,.18,7,0x4d3928,x,.16,-28);for(const z of [-29.55,-26.45])box(104,.13,.16,0x424647,0,.28,z);

const worldLabels=[];
function addWorldLabel(title,pos,subFn){const el=document.createElement('div');el.className='world-label';el.innerHTML=`${title}<small></small>`;document.getElementById('worldLabels').appendChild(el);worldLabels.push({el,pos,subFn});return el}
function building(x,z,w,d,h,label){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:palette.wood,roughness:.98}));body.position.y=h/2;body.castShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(w+1,.4,d+1),new THREE.MeshStandardMaterial({color:0x404746,roughness:.85}));roof.position.y=h+.18;roof.castShadow=true;g.add(roof);g.position.set(x,0,z);scene.add(g);addWorldLabel(label,new THREE.Vector3(x,h+1.2,z));return g}
building(-36,-11,15,12,5,'物資倉庫');building(33,-10,14,11,5,'整備庫');building(-36,13,14,12,4.7,'兵員待機所');building(31,13,14,12,4.7,'車両ヤード');

for(const [x,z,s] of [[-38,35,1],[-20,42,.9],[3,36,1.2],[23,43,.8],[40,34,1]]){const ruin=new THREE.Group();for(let i=0;i<5;i++){const b=new THREE.Mesh(new THREE.BoxGeometry((3+Math.random()*3)*s,(1.5+Math.random()*4)*s,(2+Math.random()*2)*s),new THREE.MeshStandardMaterial({color:palette.brick,roughness:1}));b.position.set((Math.random()-.5)*5,b.geometry.parameters.height/2,(Math.random()-.5)*4);b.rotation.y=(Math.random()-.5)*.4;ruin.add(b)}ruin.position.set(x,0,z);scene.add(ruin)}
const frontActors=[];for(let i=0;i<22;i++){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.26,.55,.22),new THREE.MeshStandardMaterial({color:i%2?0x59634e:0x6c6654}));body.position.y=.48;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.12,6,5),new THREE.MeshStandardMaterial({color:0x9d8065}));head.position.y=.88;g.add(head);g.position.set(-42+Math.random()*84,0,27+Math.random()*18);g.userData.phase=Math.random()*6.28;g.userData.side=i%2?1:-1;scene.add(g);frontActors.push(g)}
for(const [x,z,flip] of [[-27,36,1],[15,31,-1],[35,41,-1]]){const t=new THREE.Group();const hull=new THREE.Mesh(new THREE.BoxGeometry(3,.75,1.8),new THREE.MeshStandardMaterial({color:0x545a49}));hull.position.y=.62;t.add(hull);const turret=new THREE.Mesh(new THREE.BoxGeometry(1.35,.55,1.1),new THREE.MeshStandardMaterial({color:0x4b5143}));turret.position.y=1.25;t.add(turret);const gun=new THREE.Mesh(new THREE.BoxGeometry(2.2,.13,.13),new THREE.MeshStandardMaterial({color:0x313632}));gun.position.set(flip*1.3,1.3,0);t.add(gun);t.position.set(x,0,z);scene.add(t)}

const stations=[];
function addStation(id,label,x,z,recipe,color){const group=new THREE.Group();const bench=new THREE.Mesh(new THREE.BoxGeometry(6,1.05,4.2),new THREE.MeshStandardMaterial({color:palette.steel,roughness:.85}));bench.position.y=.55;bench.castShadow=true;group.add(bench);const top=new THREE.Mesh(new THREE.BoxGeometry(5.5,.12,3.7),new THREE.MeshStandardMaterial({color,roughness:.8}));top.position.y=1.12;group.add(top);for(let i=0;i<3;i++){const tool=new THREE.Mesh(new THREE.BoxGeometry(.65,.38,.45),new THREE.MeshStandardMaterial({color:0x343a38}));tool.position.set(-1.7+i*1.7,1.38,(i%2-.5)*1.4);group.add(tool)}group.position.set(x,0,z);scene.add(group);const st={id,label,group,pos:new THREE.Vector3(x,0,z),recipe,input:{},progress:0,processing:false,output:null,color};stations.push(st);addWorldLabel(label,new THREE.Vector3(x,2.6,z),()=>stationSubtitle(st));return st}
const rifleStation=addStation('rifle','小銃分隊 編成所',-18,-8,{personnel:1,rifles:1,ammo:1},0x7f845f);
const mgStation=addStation('mg','機関銃班 編成所',2,-8,{personnel:1,mg:1,tripod:1,ammo:1},0x7b6c55);
const mortarStation=addStation('mortar','迫撃砲班 編成所',-18,9,{personnel:1,mortar:1,shells:1},0x6d766f);
const tankStation=addStation('tank','戦車 戦闘準備所',4,9,{tank:1,personnel:1,fuel:1,shells:1},0x666e52);

const TYPE={personnel:{label:'兵員',color:0x59634e},rifles:{label:'小銃梱包',color:0x725840},ammo:{label:'小銃弾薬',color:0x7e744c},mg:{label:'機関銃',color:0x494f4a},tripod:{label:'三脚',color:0x5f5b4d},mortar:{label:'迫撃砲',color:0x545d58},shells:{label:'迫撃砲弾',color:0x6e6948},fuel:{label:'燃料',color:0x765848},tank:{label:'戦車車体',color:0x4f5b49},rifle_squad:{label:'小銃分隊',color:0x889768,prepared:true},mg_team:{label:'機関銃班',color:0x8b795b,prepared:true},mortar_team:{label:'迫撃砲班',color:0x78857a,prepared:true},tank_ready:{label:'戦車1両',color:0x65765b,prepared:true}};
const stationOutput={rifle:'rifle_squad',mg:'mg_team',mortar:'mortar_team',tank:'tank_ready'};
function stationSubtitle(st){if(st.output)return `${TYPE[st.output].label} 完成`;if(st.processing)return `準備中 ${Math.round(st.progress*100)}%`;return Object.entries(st.recipe).map(([k,n])=>`${TYPE[k].label} ${st.input[k]||0}/${n}`).join(' · ')}

const rallyPos=new THREE.Vector3(22,0,22);box(16,.14,10,0x77725e,22,.09,22);for(let x=15;x<=29;x+=2){box(.12,1.2,.12,0x4c4c44,x,.6,17.4);box(.12,1.2,.12,0x4c4c44,x,.6,26.6)}
const signalPos=new THREE.Vector3(-1,0,22);box(6,1.1,4.5,0x4c5351,-1,.55,22);box(1.2,2.3,1.2,0x363c3b,-1,1.7,22);
const rallyNeed={rifle_squad:2,mg_team:1,mortar_team:1,tank_ready:1},rallyHave={};let rallyReady=false,companyCount=0,frontStatus=72;
addWorldLabel('中隊 集合地点',new THREE.Vector3(22,2,22),()=>rallyReady?'編成完了 · 指揮所へ':'部隊をここへ運べ');addWorldLabel('指揮所 / 号令',new THREE.Vector3(-1,3.7,22),()=>rallyReady?'E：前進命令':'中隊編成待ち');

const train=new THREE.Group();function trainCar(x,w,color){const g=new THREE.Group();const car=new THREE.Mesh(new THREE.BoxGeometry(w,2.5,4.5),new THREE.MeshStandardMaterial({color,roughness:.82}));car.position.y=1.7;car.castShadow=true;g.add(car);for(const dx of [-w*.3,w*.3])for(const zz of [-1.55,1.55]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.45,.45,.28,10),new THREE.MeshStandardMaterial({color:0x242727,metalness:.4}));wheel.rotation.x=Math.PI/2;wheel.position.set(dx,.46,zz);g.add(wheel)}g.position.x=x;train.add(g)}trainCar(0,7,0x3b4543);trainCar(-8,7,0x65533e);trainCar(-16,7,0x66523e);trainCar(-24,7,0x5d4c3c);train.position.set(-68,0,-28);scene.add(train);let trainPhase='arriving',trainTimer=0,cargoSpawned=false;addWorldLabel('鉄道荷下ろし場',new THREE.Vector3(-15,3.2,-24));

const crates=[];let crateSeq=0;
function createCrate(type,x,z){const def=TYPE[type],large=type==='tank',mesh=new THREE.Group();if(large){const hull=new THREE.Mesh(new THREE.BoxGeometry(3.2,.9,2),new THREE.MeshStandardMaterial({color:def.color,roughness:.9}));hull.position.y=.72;mesh.add(hull);const turret=new THREE.Mesh(new THREE.BoxGeometry(1.5,.55,1.2),new THREE.MeshStandardMaterial({color:0x465143}));turret.position.y=1.4;mesh.add(turret)}else{const c=new THREE.Mesh(new THREE.BoxGeometry(1.15,.82,.9),new THREE.MeshStandardMaterial({color:def.color,roughness:.95}));c.position.y=.48;c.castShadow=true;mesh.add(c);const band=new THREE.Mesh(new THREE.BoxGeometry(1.22,.09,.96),new THREE.MeshStandardMaterial({color:0x343530,roughness:.8}));band.position.y=.56;mesh.add(band)}mesh.position.set(x,0,z);scene.add(mesh);const item={id:++crateSeq,type,mesh,carried:false};crates.push(item);return item}
function spawnCargoBatch(){const manifest=['personnel','personnel','personnel','personnel','personnel','rifles','rifles','ammo','ammo','ammo','mg','tripod','mortar','shells','shells','fuel','tank'];manifest.forEach((t,i)=>createCrate(t,-42+(i%6)*3.2,-21+Math.floor(i/6)*2.6));notify('貨物列車到着：荷下ろし開始')}

const player=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.75,1.15,.55),new THREE.MeshStandardMaterial({color:0x59634e,roughness:.9}));body.position.y=1.05;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,8,7),new THREE.MeshStandardMaterial({color:0xa9886b}));head.position.y=1.82;player.add(head);const cap=new THREE.Mesh(new THREE.BoxGeometry(.65,.18,.65),new THREE.MeshStandardMaterial({color:0x474f42}));cap.position.y=2.04;player.add(cap);const pack=new THREE.Mesh(new THREE.BoxGeometry(.55,.72,.28),new THREE.MeshStandardMaterial({color:0x5e5744}));pack.position.set(0,1.04,.42);player.add(pack);player.position.set(-5,0,-1);scene.add(player);let carrying=null;

function updateLabels(){const w=innerWidth,h=innerHeight;for(const l of worldLabels){const v=l.pos.clone().project(camera);l.el.style.left=`${(v.x*.5+.5)*w}px`;l.el.style.top=`${(-v.y*.5+.5)*h}px`;l.el.style.display=v.z>1?'none':'block';if(l.subFn)l.el.querySelector('small').textContent=l.subFn()}}
const keys=new Set();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact()});addEventListener('keyup',e=>keys.delete(e.code));
const companyCountEl=document.getElementById('companyCount'),frontValue=document.getElementById('frontValue'),frontFill=document.getElementById('frontFill'),frontMessage=document.getElementById('frontMessage'),carryText=document.getElementById('carryText'),nearText=document.getElementById('nearText'),recipeList=document.getElementById('recipeList'),companyReady=document.getElementById('companyReady'),toast=document.getElementById('toast'),prompt=document.getElementById('interactPrompt'),promptText=prompt.querySelector('span');
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1300)}
function recipeUI(){recipeList.innerHTML='';for(const [k,n] of Object.entries(rallyNeed)){const have=rallyHave[k]||0,d=document.createElement('div');d.className='recipe-item'+(have>=n?' done':'');d.innerHTML=`<span>${TYPE[k].label}</span><strong>${have} / ${n}</strong>`;recipeList.appendChild(d)}companyReady.textContent=rallyReady?'編成完了：指揮所で号令可能':'集合地点で編成中';companyReady.classList.toggle('ready',rallyReady)}recipeUI();
function distXZ(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
function stationPrompt(st){if(st.output&&!carrying)return `${TYPE[st.output].label}を受け取る`;if(carrying&&st.recipe[carrying.type])return `${TYPE[carrying.type].label}を投入`;if(st.processing)return '準備中';return st.label}
function nearestContext(){let best=null,bestD=3.2;for(const c of crates){if(c.carried)continue;const d=distXZ(player.position,c.mesh.position);if(d<bestD){bestD=d;best={kind:'crate',obj:c,label:`${TYPE[c.type].label}を拾う`}}}for(const st of stations){const d=distXZ(player.position,st.pos);if(d<bestD){bestD=d;best={kind:'station',obj:st,label:stationPrompt(st)}}}let d=distXZ(player.position,rallyPos);if(d<bestD){bestD=d;best={kind:'rally',label:carrying&&TYPE[carrying.type]?.prepared?`${TYPE[carrying.type].label}を集合地点へ`:'集合地点'}}d=distXZ(player.position,signalPos);if(d<bestD){best={kind:'signal',label:rallyReady?'前進命令を出す':'編成完了を待つ'}}return best}
function pickup(item){carrying=item;item.carried=true;notify(`${TYPE[item.type].label}を持った`)}
function dropCarried(){if(!carrying)return;carrying.carried=false;carrying.mesh.position.set(player.position.x+Math.sin(player.rotation.y)*1.5,0,player.position.z+Math.cos(player.rotation.y)*1.5);carrying=null}
function consumeCarried(){if(!carrying)return;scene.remove(carrying.mesh);const i=crates.indexOf(carrying);if(i>=0)crates.splice(i,1);carrying=null}
function makeOutput(st){const type=stationOutput[st.id],out=createCrate(type,st.pos.x,st.pos.z+3);out.mesh.visible=false;out.carried=true;st.output=type;st.outputItem=out;notify(`${TYPE[type].label} 完成`)}
function startIfReady(st){if(st.processing||st.output)return;for(const [k,n] of Object.entries(st.recipe))if((st.input[k]||0)<n)return;st.processing=true;st.progress=0;notify(`${st.label}：準備開始`)}
function interact(){const ctx=nearestContext();if(!ctx){if(carrying){dropCarried();notify('地面に置いた')}return}if(ctx.kind==='crate'&&!carrying){pickup(ctx.obj);return}if(ctx.kind==='station'){const st=ctx.obj;if(st.output&&!carrying){const item=st.outputItem;item.mesh.visible=true;item.carried=true;carrying=item;st.output=null;st.outputItem=null;for(const k of Object.keys(st.recipe))st.input[k]=0;notify(`${TYPE[carrying.type].label}を受け取った`);return}if(carrying&&st.recipe[carrying.type]){const type=carrying.type;st.input[type]=(st.input[type]||0)+1;consumeCarried();notify(`${TYPE[type].label} 投入`);startIfReady(st);return}}if(ctx.kind==='rally'&&carrying&&TYPE[carrying.type]?.prepared){const type=carrying.type;if(rallyNeed[type]){rallyHave[type]=(rallyHave[type]||0)+1;consumeCarried();notify(`${TYPE[type].label} 集合`);rallyReady=Object.entries(rallyNeed).every(([k,n])=>(rallyHave[k]||0)>=n);recipeUI();return}}if(ctx.kind==='signal'&&rallyReady){dispatchCompany();return}if(carrying){dropCarried();notify('地面に置いた')}}

function createConvoy(){const g=new THREE.Group();const tank=new THREE.Mesh(new THREE.BoxGeometry(3,.8,1.8),new THREE.MeshStandardMaterial({color:0x59634e}));tank.position.set(0,.65,0);g.add(tank);for(let j=0;j<2;j++){const truck=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.4,1.5),new THREE.MeshStandardMaterial({color:0x64654f}));truck.position.set(-3.5-j*3,.8,0);g.add(truck)}for(let i=0;i<8;i++){const s=new THREE.Mesh(new THREE.BoxGeometry(.25,.6,.22),new THREE.MeshStandardMaterial({color:0x59634e}));s.position.set(-3-(i%4)*.55,1.8+(i>3?.1:0),(i%2-.5)*.6);g.add(s)}g.position.set(22,0,22);scene.add(g);return g}
const convoys=[];function dispatchCompany(){rallyReady=false;companyCount++;companyCountEl.textContent=`${companyCount} 中隊`;for(const k of Object.keys(rallyHave))rallyHave[k]=0;recipeUI();frontStatus=Math.min(100,frontStatus+21);notify(`第${companyCount}増強中隊：前進！`);convoys.push({mesh:createConvoy(),t:0})}
function updateTrain(dt){trainTimer+=dt;if(trainPhase==='arriving'){train.position.x+=dt*7.5;if(train.position.x>=12){train.position.x=12;trainPhase='stopped';trainTimer=0;if(!cargoSpawned){spawnCargoBatch();cargoSpawned=true}}}else if(trainPhase==='stopped'){if(trainTimer>13){trainPhase='leaving';trainTimer=0}}else if(trainPhase==='leaving'){train.position.x+=dt*9;if(train.position.x>72){train.position.x=-68;trainPhase='arriving';trainTimer=0;cargoSpawned=false}}}
function updateStations(dt){for(const st of stations)if(st.processing){st.progress=Math.min(1,st.progress+dt/(st.id==='tank'?5.5:3.5));st.group.children[1].scale.x=.92+.12*Math.sin(performance.now()*.015);if(st.progress>=1){st.processing=false;st.progress=0;st.group.children[1].scale.x=1;makeOutput(st)}}}
function updateConvoys(dt){for(let i=convoys.length-1;i>=0;i--){const c=convoys[i];c.mesh.position.z+=dt*5.8;c.mesh.position.x-=dt*.55;if(c.mesh.position.z>49){scene.remove(c.mesh);convoys.splice(i,1)}}}
function updateFront(dt,now){frontStatus=Math.max(0,frontStatus-dt*.16);frontValue.textContent=`${Math.round(frontStatus)}%`;frontFill.style.width=`${frontStatus}%`;frontFill.style.background=frontStatus<30?'#b96255':'linear-gradient(90deg,#9cad7f,#d5c27c)';frontMessage.textContent=frontStatus<35?'前線崩壊寸前：増援急げ':frontStatus<60?'損耗拡大：増援要請':'前線から増援要請';for(const a of frontActors){a.position.x+=Math.sin(now*.001+a.userData.phase)*dt*.2*a.userData.side;a.rotation.y+=Math.sin(now*.0007+a.userData.phase)*dt*.08}}
function movePlayer(dt){let x=0,z=0;if(keys.has('KeyW')||keys.has('ArrowUp'))z+=1;if(keys.has('KeyS')||keys.has('ArrowDown'))z-=1;if(keys.has('KeyA')||keys.has('ArrowLeft'))x-=1;if(keys.has('KeyD')||keys.has('ArrowRight'))x+=1;if(x||z){const len=Math.hypot(x,z);x/=len;z/=len;const sp=(keys.has('ShiftLeft')||keys.has('ShiftRight')?10.5:7.1)*dt;player.position.x+=x*sp;player.position.z+=z*sp;player.rotation.y=Math.atan2(x,z);body.position.y=1.05+Math.abs(Math.sin(performance.now()*.012))*.05}else body.position.y=1.05;player.position.x=THREE.MathUtils.clamp(player.position.x,-48,48);player.position.z=THREE.MathUtils.clamp(player.position.z,-23,29);if(carrying){carrying.mesh.visible=true;carrying.mesh.position.set(player.position.x,2.6,player.position.z);carrying.mesh.rotation.y=player.rotation.y}}
function updateHud(){carryText.textContent=carrying?TYPE[carrying.type].label:'手ぶら';const ctx=nearestContext();nearText.textContent=ctx?ctx.label:(carrying?'E：地面に置く':'物資に近づいて E');if(ctx){prompt.classList.add('show');promptText.textContent=ctx.label}else prompt.classList.remove('show')}
let last=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-last)/1000);last=now;movePlayer(dt);updateTrain(dt);updateStations(dt);updateConvoys(dt);updateFront(dt,now);updateHud();updateLabels();renderer.render(scene,camera)}
if(!(matchMedia('(pointer:fine)').matches&&innerWidth>=900)){const h=document.getElementById('pcHint');h.classList.add('active');setTimeout(()=>h.classList.remove('active'),4500)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});requestAnimationFrame(loop);
