import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {createWorld,heightAt} from './world.js';
import {createLandingCraft,createSquad,orderSquadMove,prepareSquadAttack,updateSquadVisual,SQUAD_SIZE} from './units.js';
const SQUAD_COST=30;
const isPC=matchMedia('(pointer:fine)').matches&&innerWidth>=900;if(!isPC){const h=document.getElementById('pcHint');h.classList.add('active');setTimeout(()=>h.classList.remove('active'),4200)}
const game=document.getElementById('game'),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;game.appendChild(renderer.domElement);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
const scene=new THREE.Scene(),world=createWorld(scene),camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.1,600);const camTarget=new THREE.Vector3(0,3,-6);let camYaw=Math.PI,camPitch=.34,camDistance=86;function updateCamera(){camPitch=THREE.MathUtils.clamp(camPitch,.22,1.42);camDistance=THREE.MathUtils.clamp(camDistance,18,165);const cp=Math.cos(camPitch);camera.position.set(camTarget.x+Math.sin(camYaw)*cp*camDistance,camTarget.y+Math.sin(camPitch)*camDistance,camTarget.z+Math.cos(camYaw)*cp*camDistance);camera.lookAt(camTarget)}updateCamera();
let supply=42,seq=0,selected=null;const squads=[],landings=[];const deploy=document.getElementById('deployBtn'),supplyText=document.getElementById('supplyText'),supplyFill=document.getElementById('supplyFill'),selection=document.getElementById('selection'),selectionTitle=document.getElementById('selectionTitle'),selectionMeta=document.getElementById('selectionMeta'),selectionState=document.getElementById('selectionState'),toast=document.getElementById('toast'),crosshair=document.getElementById('crosshair');deploy.textContent=`歩兵分隊　${SQUAD_COST}`;function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),950)}function ui(){supply=Math.min(500,supply);supplyText.textContent=`${Math.floor(supply)} / 500`;supplyFill.style.width=`${supply/5}%`;deploy.disabled=supply<SQUAD_COST}function stateText(){if(!selected)return;const s=selected.userData.state;selectionState.textContent=s==='fire'?'交戦中':s==='move'?'移動中':s==='landingScatter'?'上陸・散開中':'警戒'}
function deploySquad(){if(supply<SQUAD_COST)return;supply-=SQUAD_COST;ui();const id=++seq,beachX=-30+((id*17)%60),craft=[createLandingCraft(scene,-8+(id%4)*5,-61-(id%2)*3)];landings.push({id,craft,t:0,phase:'sea',beachX,startX:craft[0].position.x,startZ:craft[0].position.z});notify(`第${id}分隊 上陸開始`)}deploy.addEventListener('click',deploySquad);
function select(s){if(selected?.userData.ring)selected.userData.ring.visible=false;selected=s;s.userData.ring.visible=true;selection.classList.add('active');selectionTitle.textContent=`第${s.userData.id}分隊`;selectionMeta.textContent=`${SQUAD_SIZE}名`;stateText()}
function moveOrder(p){if(!selected)return;orderSquadMove(selected,new THREE.Vector3(p.x,heightAt(p.x,p.z),p.z));stateText();notify(`第${selected.userData.id}分隊 移動`)}
const MAX=420,tracerPos=new Float32Array(MAX*6),flashPos=new Float32Array(MAX*3),life=new Float32Array(MAX);tracerPos.fill(-999);flashPos.fill(-999);const tracerGeo=new THREE.BufferGeometry();tracerGeo.setAttribute('position',new THREE.BufferAttribute(tracerPos,3));scene.add(new THREE.LineSegments(tracerGeo,new THREE.LineBasicMaterial({color:0xffd36d,transparent:true,opacity:.78})));const flashGeo=new THREE.BufferGeometry();flashGeo.setAttribute('position',new THREE.BufferAttribute(flashPos,3));scene.add(new THREE.Points(flashGeo,new THREE.PointsMaterial({color:0xffd56c,size:.16})));let cursor=0;
function shot(root,s,target,now){const slot=cursor++%MAX,m=new THREE.Vector3(s.x,s.renderY+1.12,s.z);root.localToWorld(m);const aim=target.clone();aim.x+=(Math.random()-.5)*2.2;aim.y+=.45+Math.random()*1.05;aim.z+=(Math.random()-.5)*2.2;const d=aim.sub(m).normalize(),end=m.clone().addScaledVector(d,8+Math.random()*9);let k=slot*6;[m.x,m.y,m.z,end.x,end.y,end.z].forEach(v=>tracerPos[k++]=v);k=slot*3;[m.x,m.y,m.z].forEach(v=>flashPos[k++]=v);life[slot]=now+65;tracerGeo.attributes.position.needsUpdate=true;flashGeo.attributes.position.needsUpdate=true;s.lastShot=now}
function attack(p,x,y){if(!selected)return;prepareSquadAttack(selected,p);stateText();crosshair.style.left=`${x}px`;crosshair.style.top=`${y}px`;crosshair.style.display='block';setTimeout(()=>crosshair.style.display='none',900);notify(`第${selected.userData.id}分隊 攻撃`)}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function rayEvent(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera)}let drag=false,last={x:0,y:0},clickTimer=0;renderer.domElement.addEventListener('mousedown',e=>{last={x:e.clientX,y:e.clientY};if(e.button===2)drag=true});addEventListener('mouseup',e=>{if(e.button===2)drag=false});addEventListener('mousemove',e=>{if(!drag)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};camYaw-=dx*.006;camPitch+=dy*.0045;updateCamera()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();camDistance+=e.deltaY*.055;updateCamera()},{passive:false});renderer.domElement.addEventListener('click',e=>{if(e.button!==0)return;rayEvent(e);const h=ray.intersectObjects(squads,true);if(h.length){let o=h[0].object;while(o.parent&&o.userData.type!=='squad')o=o.parent;if(o.userData.type==='squad'){clearTimeout(clickTimer);select(o);return}}const p=ray.intersectObjects([world.land,world.beach],false)[0]?.point;if(!p||!selected)return;clearTimeout(clickTimer);clickTimer=setTimeout(()=>moveOrder(p),230)});renderer.domElement.addEventListener('dblclick',e=>{if(e.button!==0||!selected)return;clearTimeout(clickTimer);rayEvent(e);const p=ray.intersectObjects([world.land,world.beach],false)[0]?.point;if(p)attack(p,e.clientX,e.clientY)});
const keys=new Set();addEventListener('keydown',e=>keys.add(e.code));addEventListener('keyup',e=>keys.delete(e.code));function freeCam(dt){let f=0,r=0;if(keys.has('KeyW'))f++;if(keys.has('KeyS'))f--;if(keys.has('KeyD'))r++;if(keys.has('KeyA'))r--;if(keys.has('KeyQ'))camYaw+=dt*1.1;if(keys.has('KeyE'))camYaw-=dt*1.1;if(!f&&!r&&!keys.has('KeyQ')&&!keys.has('KeyE'))return;const sp=(keys.has('ShiftLeft')||keys.has('ShiftRight')?40:18)*dt,fw=new THREE.Vector3(-Math.sin(camYaw),0,-Math.cos(camYaw)),rt=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));camTarget.addScaledVector(fw,f*sp).addScaledVector(rt,r*sp);camTarget.x=THREE.MathUtils.clamp(camTarget.x,-62,62);camTarget.z=THREE.MathUtils.clamp(camTarget.z,-66,104);camTarget.y=Math.max(0,heightAt(camTarget.x,camTarget.z));updateCamera()}
function updateLandings(dt){for(let i=landings.length-1;i>=0;i--){const g=landings[i];g.t+=dt;if(g.phase==='sea'){const t=Math.min(1,g.t/8.4),s=t*t*(3-2*t),c=g.craft[0];c.position.x=THREE.MathUtils.lerp(g.startX,g.beachX,s);c.position.z=THREE.MathUtils.lerp(g.startZ,-5.5,s);if(t>=1){g.phase='unload';g.t=0;g.unit=createSquad(scene,g.id,g.beachX,2.8,heightAt);squads.push(g.unit);g.unit.scale.setScalar(.03)}}else{const t=Math.min(1,g.t/1.4);g.unit.scale.setScalar(.03+.97*t);g.craft[0].position.z-=dt*4.8;if(t>=1){scene.remove(g.craft[0]);landings.splice(i,1);notify(`第${g.id}分隊 上陸完了`)}}}}
function updateSquads(dt,now){for(const s of squads){const before=s.userData.state;updateSquadVisual(s,now,dt);if(before!==s.userData.state&&s===selected)stateText();if(s.userData.state==='fire'&&now<s.userData.fireUntil){for(const man of s.userData.soldiers){if(now<man.attackReady)continue;if(now>=man.nextShot){shot(s,man,s.userData.attackPoint,now);const b=man.weapon==='BAR'?.15:man.weapon==='Thompson'?.11:.52;man.nextShot=now+(b+Math.random()*b*1.15)*1000}}}}}
function updateShots(now){for(let i=0;i<MAX;i++)if(life[i]&&now>life[i]){life[i]=0;let k=i*6;for(let j=0;j<6;j++)tracerPos[k+j]=-999;k=i*3;for(let j=0;j<3;j++)flashPos[k+j]=-999;tracerGeo.attributes.position.needsUpdate=true;flashGeo.attributes.position.needsUpdate=true}}
let lastT=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-lastT)/1000);lastT=now;supply+=dt*9;ui();freeCam(dt);updateLandings(dt);updateSquads(dt,now);updateShots(now);renderer.render(scene,camera)}ui();requestAnimationFrame(loop);addEventListener('resize',()=>{if(innerWidth<900){const h=document.getElementById('pcHint');h.classList.add('active');setTimeout(()=>h.classList.remove('active'),3000)}camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
