import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {createWorld,heightAt} from './world.js';
import {createLandingCraft,createCompany,updateCompanyVisual} from './units.js';
const isPC=matchMedia('(pointer:fine)').matches&&innerWidth>=900;if(!isPC){const h=document.getElementById('pcHint');h.classList.add('active');setTimeout(()=>h.classList.remove('active'),4200)}
const game=document.getElementById('game'),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;game.appendChild(renderer.domElement);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
const scene=new THREE.Scene(),world=createWorld(scene),camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,.1,600);const camTarget=new THREE.Vector3(0,3,-6);let camYaw=Math.PI,camPitch=.34,camDistance=86;function updateCamera(){camPitch=THREE.MathUtils.clamp(camPitch,.22,1.42);camDistance=THREE.MathUtils.clamp(camDistance,18,165);const cp=Math.cos(camPitch);camera.position.set(camTarget.x+Math.sin(camYaw)*cp*camDistance,camTarget.y+Math.sin(camPitch)*camDistance,camTarget.z+Math.cos(camYaw)*cp*camDistance);camera.lookAt(camTarget)}updateCamera();
let supply=42,seq=0,selected=null;const companies=[],landings=[];const deploy=document.getElementById('deployBtn'),supplyText=document.getElementById('supplyText'),supplyFill=document.getElementById('supplyFill'),selection=document.getElementById('selection'),selectionTitle=document.getElementById('selectionTitle'),selectionMeta=document.getElementById('selectionMeta'),selectionState=document.getElementById('selectionState'),toast=document.getElementById('toast'),crosshair=document.getElementById('crosshair');function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),950)}function ui(){supply=Math.min(500,supply);supplyText.textContent=`${Math.floor(supply)} / 500`;supplyFill.style.width=`${supply/5}%`;deploy.disabled=supply<100}function stateText(){if(!selected)return;const s=selected.userData.state;selectionState.textContent=s==='fire'?'攻撃中':s==='move'?'移動中':s==='landingScatter'?'散開中':'待機'}
function deployCompany(){if(supply<100)return;supply-=100;ui();const id=++seq,craft=[];for(let i=0;i<6;i++)craft.push(createLandingCraft(scene,-11+i*4.4,-58-(i%2)*3.2));landings.push({id,craft,t:0,phase:'sea',beachX:-27+((id*19)%54)});notify(`第${id}中隊 上陸開始`)}deploy.addEventListener('click',deployCompany);
function select(c){if(selected?.userData.ring)selected.userData.ring.visible=false;selected=c;c.userData.ring.visible=true;selection.classList.add('active');selectionTitle.textContent=`第${c.userData.id}中隊`;selectionMeta.textContent='193名';stateText()}
function moveOrder(p){if(!selected)return;selected.userData.target.set(p.x,heightAt(p.x,p.z),p.z);selected.userData.state='move';selected.userData.attackPoint=null;selected.userData.soldiers.forEach(s=>{s.posture='run';s.settled=true});stateText();notify(`第${selected.userData.id}中隊 移動`)}
const MAX=420,tracerPos=new Float32Array(MAX*6),flashPos=new Float32Array(MAX*3),life=new Float32Array(MAX);tracerPos.fill(-999);flashPos.fill(-999);const tracerGeo=new THREE.BufferGeometry();tracerGeo.setAttribute('position',new THREE.BufferAttribute(tracerPos,3));scene.add(new THREE.LineSegments(tracerGeo,new THREE.LineBasicMaterial({color:0xffd36d,transparent:true,opacity:.78})));const flashGeo=new THREE.BufferGeometry();flashGeo.setAttribute('position',new THREE.BufferAttribute(flashPos,3));scene.add(new THREE.Points(flashGeo,new THREE.PointsMaterial({color:0xffd56c,size:.16})));let cursor=0;
function shot(root,s,target,now){const slot=cursor++%MAX,m=new THREE.Vector3(s.x+.05,1.15,s.z-(s.weapon==='Thompson'?.7:s.weapon==='BAR'?1.18:.94));root.localToWorld(m);const aim=target.clone();aim.x+=(Math.random()-.5)*3;aim.y+=.6+Math.random()*1.5;aim.z+=(Math.random()-.5)*3;const d=aim.sub(m).normalize(),end=m.clone().addScaledVector(d,8+Math.random()*9);let k=slot*6;[m.x,m.y,m.z,end.x,end.y,end.z].forEach(v=>tracerPos[k++]=v);k=slot*3;[m.x,m.y,m.z].forEach(v=>flashPos[k++]=v);life[slot]=now+65;tracerGeo.attributes.position.needsUpdate=true;flashGeo.attributes.position.needsUpdate=true;s.lastShot=now}
function attack(p,x,y){if(!selected)return;selected.userData.attackPoint=p.clone();selected.userData.state='fire';selected.userData.fireUntil=performance.now()+5200;const d=p.clone().sub(selected.position);selected.rotation.y=Math.atan2(d.x,d.z);stateText();crosshair.style.left=`${x}px`;crosshair.style.top=`${y}px`;crosshair.style.display='block';setTimeout(()=>crosshair.style.display='none',900);notify(`第${selected.userData.id}中隊 一斉射撃`)}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function rayEvent(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera)}let drag=false,last={x:0,y:0},clickTimer=0;renderer.domElement.addEventListener('mousedown',e=>{last={x:e.clientX,y:e.clientY};if(e.button===2)drag=true});addEventListener('mouseup',e=>{if(e.button===2)drag=false});addEventListener('mousemove',e=>{if(!drag)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};camYaw-=dx*.006;camPitch+=dy*.0045;updateCamera()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();camDistance+=e.deltaY*.055;updateCamera()},{passive:false});renderer.domElement.addEventListener('click',e=>{if(e.button!==0)return;rayEvent(e);const h=ray.intersectObjects(companies,true);if(h.length){let o=h[0].object;while(o.parent&&o.userData.type!=='company')o=o.parent;if(o.userData.type==='company'){clearTimeout(clickTimer);select(o);return}}const p=ray.intersectObjects([world.land,world.beach],false)[0]?.point;if(!p||!selected)return;clearTimeout(clickTimer);clickTimer=setTimeout(()=>moveOrder(p),230)});renderer.domElement.addEventListener('dblclick',e=>{if(e.button!==0||!selected)return;clearTimeout(clickTimer);rayEvent(e);const p=ray.intersectObjects([world.land,world.beach],false)[0]?.point;if(p)attack(p,e.clientX,e.clientY)});
const keys=new Set();addEventListener('keydown',e=>keys.add(e.code));addEventListener('keyup',e=>keys.delete(e.code));function freeCam(dt){let f=0,r=0;if(keys.has('KeyW'))f++;if(keys.has('KeyS'))f--;if(keys.has('KeyD'))r++;if(keys.has('KeyA'))r--;if(keys.has('KeyQ'))camYaw+=dt*1.1;if(keys.has('KeyE'))camYaw-=dt*1.1;if(!f&&!r&&!keys.has('KeyQ')&&!keys.has('KeyE'))return;const sp=(keys.has('ShiftLeft')||keys.has('ShiftRight')?40:18)*dt,fw=new THREE.Vector3(-Math.sin(camYaw),0,-Math.cos(camYaw)),rt=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));camTarget.addScaledVector(fw,f*sp).addScaledVector(rt,r*sp);camTarget.x=THREE.MathUtils.clamp(camTarget.x,-62,62);camTarget.z=THREE.MathUtils.clamp(camTarget.z,-66,78);camTarget.y=Math.max(0,heightAt(camTarget.x,camTarget.z));updateCamera()}
function updateLandings(dt){for(let i=landings.length-1;i>=0;i--){const g=landings[i];g.t+=dt;if(g.phase==='sea'){const t=Math.min(1,g.t/9.2),s=t*t*(3-2*t);g.craft.forEach((c,j)=>{c.position.x=THREE.MathUtils.lerp(-11+j*4.4,g.beachX+(j-2.5)*2.2,s);c.position.z=THREE.MathUtils.lerp(-58-(j%2)*3.2,-7+(j%2),s)});if(t>=1){g.phase='unload';g.t=0;g.unit=createCompany(scene,g.id,g.beachX,1.6,heightAt);companies.push(g.unit);g.unit.scale.setScalar(.02)}}else{const t=Math.min(1,g.t/1.7);g.unit.scale.setScalar(.02+.98*t);g.craft.forEach(c=>c.position.z-=dt*4.4);if(t>=1){g.craft.forEach(c=>scene.remove(c));landings.splice(i,1);notify(`第${g.id}中隊 上陸完了`)}}}}
function updateCompanies(dt,now){for(const c of companies){let motion=0;if(c.userData.state==='landingScatter'&&now-c.userData.landedAt>12500){c.userData.state='idle';c.userData.soldiers.forEach(s=>{const q=Math.random();s.posture=q<.34?'prone':q<.62?'cover':'run'});if(c===selected)stateText()}if(c.userData.state==='move'){const d=new THREE.Vector3(c.userData.target.x-c.position.x,0,c.userData.target.z-c.position.z),dist=d.length();if(dist>.35){d.normalize();c.position.addScaledVector(d,Math.min(dist,c.userData.speed*dt));c.rotation.y=Math.atan2(d.x,d.z);c.position.y=heightAt(c.position.x,c.position.z);motion=1}else{c.userData.state='idle';if(c===selected)stateText()}}if(c.userData.state==='fire'){if(now>=c.userData.fireUntil){c.userData.state='idle';if(c===selected)stateText()}else c.userData.soldiers.forEach(s=>{if(now>=s.nextShot){shot(c,s,c.userData.attackPoint,now);const b=s.weapon==='BAR'?.13:s.weapon==='Thompson'?.095:.48;s.nextShot=now+(b+Math.random()*b*.9)*1000}})}updateCompanyVisual(c,now,motion)}}
function updateShots(now){for(let i=0;i<MAX;i++)if(life[i]&&now>life[i]){life[i]=0;let k=i*6;for(let j=0;j<6;j++)tracerPos[k+j]=-999;k=i*3;for(let j=0;j<3;j++)flashPos[k+j]=-999;tracerGeo.attributes.position.needsUpdate=true;flashGeo.attributes.position.needsUpdate=true}}
let lastT=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,(now-lastT)/1000);lastT=now;supply+=dt*9;ui();freeCam(dt);updateLandings(dt);updateCompanies(dt,now);updateShots(now);renderer.render(scene,camera)}ui();requestAnimationFrame(loop);addEventListener('resize',()=>{if(innerWidth<900){const h=document.getElementById('pcHint');h.classList.add('active');setTimeout(()=>h.classList.remove('active'),3000)}camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
