import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
export const COAST=7;
export function heightAt(x,z){if(z<COAST)return 0;const i=z-COAST;return 1+Math.min(9,i*.145)+Math.sin(x*.105)*.65+Math.sin(z*.083+x*.037)*.48+Math.cos(x*.041-z*.062)*.36}
export function createWorld(scene){
 const sky=new THREE.Mesh(new THREE.SphereGeometry(420,24,12),new THREE.MeshBasicMaterial({color:0x8aa0a5,side:THREE.BackSide}));scene.add(sky);scene.fog=new THREE.FogExp2(0xaab4af,.0038);scene.add(new THREE.HemisphereLight(0xdce8e7,0x453f31,1.55));const sun=new THREE.DirectionalLight(0xffe8bd,2.7);sun.position.set(-65,105,42);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=110;sun.shadow.camera.bottom=-110;scene.add(sun);
 const waterMat=new THREE.MeshStandardMaterial({color:0x315e6c,roughness:.28,metalness:.05});const water=new THREE.Mesh(new THREE.PlaneGeometry(128,78,30,18).rotateX(-Math.PI/2),waterMat);water.position.set(0,-.18,-34);scene.add(water);
 const beach=new THREE.Mesh(new THREE.PlaneGeometry(128,20).rotateX(-Math.PI/2),new THREE.MeshStandardMaterial({color:0xb7a376,roughness:1}));beach.position.y=.02;beach.receiveShadow=true;beach.userData.ground=true;scene.add(beach);
 const g=new THREE.PlaneGeometry(128,72,72,42);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let n=0;n<p.count;n++){const x=p.getX(n),z=p.getZ(n)+42;p.setY(n,heightAt(x,z))}g.computeVertexNormals();const land=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x65764f,roughness:1}));land.position.z=42;land.receiveShadow=true;land.userData.ground=true;scene.add(land);
 const hedgeMat=new THREE.MeshStandardMaterial({color:0x294228,roughness:1});for(const z of [24,40,57,71])for(const x of [-30,30]){const h=new THREE.Mesh(new THREE.BoxGeometry(40,2.3,1.5),hedgeMat);h.position.set(x,heightAt(x,z)+1.1,z);h.castShadow=true;scene.add(h)}
 const roadMat=new THREE.MeshStandardMaterial({color:0x746b5d,roughness:1});for(const [x,z,r] of [[-6,42,.08],[30,50,-.4]]){const m=new THREE.Mesh(new THREE.PlaneGeometry(4,66).rotateX(-Math.PI/2),roadMat);m.position.set(x,heightAt(x,z)+.08,z);m.rotation.y=r;scene.add(m)}
 for(let i=0;i<55;i++){const z=16+Math.random()*65,x=-58+Math.random()*116;if(Math.abs(x+6)<6)continue;const t=new THREE.Group();const tr=new THREE.Mesh(new THREE.CylinderGeometry(.18,.28,2.2,6),new THREE.MeshStandardMaterial({color:0x493725}));tr.position.y=1.1;t.add(tr);const cr=new THREE.Mesh(new THREE.IcosahedronGeometry(1.4,1),new THREE.MeshStandardMaterial({color:0x39533a}));cr.position.y=3;t.add(cr);t.position.set(x,heightAt(x,z),z);scene.add(t)}
 for(let i=0;i<24;i++){const x=-55+Math.random()*110,z=-3+Math.random()*26;const c=new THREE.Mesh(new THREE.RingGeometry(.4,1.5,16).rotateX(-Math.PI/2),new THREE.MeshStandardMaterial({color:0x453d31,side:THREE.DoubleSide}));c.position.set(x,z<COAST?.06:heightAt(x,z)+.06,z);scene.add(c)}
 for(let i=0;i<22;i++){const o=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x414641,metalness:.3});for(let j=0;j<3;j++){const b=new THREE.Mesh(new THREE.BoxGeometry(.22,3.4,.22),mat);b.rotation.z=j*Math.PI/3;o.add(b)}o.position.set(-57+i*5.3,.8,-2-(i%3)*3);scene.add(o)}
 for(const [x,z] of [[-40,14],[-14,12],[17,12],[44,14]]){const b=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x5d6058,roughness:1});const q=new THREE.Mesh(new THREE.BoxGeometry(8,2.8,5),mat);q.position.y=1.4;b.add(q);const roof=new THREE.Mesh(new THREE.BoxGeometry(9,.65,6),mat);roof.position.y=2.95;b.add(roof);b.position.set(x,heightAt(x,z),z);b.rotation.y=Math.PI;scene.add(b)}
 const carrier=createCarrier(scene,0,-55);createEscort(scene,-39,-48,.82);createEscort(scene,36,-58,.9);createEscort(scene,50,-44,.68);return{land,beach,water,carrier};
}
function createCarrier(scene,x,z){const g=new THREE.Group(),steel=new THREE.MeshStandardMaterial({color:0x3b474d,roughness:.58,metalness:.26}),deckM=new THREE.MeshStandardMaterial({color:0x596368,roughness:.9}),dark=new THREE.MeshStandardMaterial({color:0x253137,roughness:.6,metalness:.3});const hull=new THREE.Mesh(new THREE.BoxGeometry(40,3.5,6.4),steel);hull.position.y=1.25;hull.castShadow=true;g.add(hull);const bow=new THREE.Mesh(new THREE.ConeGeometry(3.2,7,4),steel);bow.rotation.z=-Math.PI/2;bow.rotation.y=Math.PI/4;bow.position.set(22,1.3,0);g.add(bow);const deck=new THREE.Mesh(new THREE.BoxGeometry(45,.55,10.5),deckM);deck.position.y=3.45;g.add(deck);const island=new THREE.Mesh(new THREE.BoxGeometry(5.4,7,3.4),steel);island.position.set(5.5,6.9,3.1);g.add(island);const bridge=new THREE.Mesh(new THREE.BoxGeometry(6.2,1.2,4),steel);bridge.position.set(5.2,10.1,2.9);g.add(bridge);const funnel=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.4,4.6,8),dark);funnel.position.set(2.8,11.2,2.6);g.add(funnel);const mast=new THREE.Mesh(new THREE.CylinderGeometry(.14,.18,7.5,6),dark);mast.position.set(6,14,2.8);g.add(mast);const radar=new THREE.Mesh(new THREE.BoxGeometry(3.8,.14,1.1),dark);radar.position.set(6,17,2.8);g.add(radar);for(const zz of [-4.1,4.1])for(const xx of [-14,-4,12]){const gun=new THREE.Mesh(new THREE.BoxGeometry(2.6,.25,.25),dark);gun.position.set(xx,4,zz);gun.rotation.y=zz>0?0:Math.PI;g.add(gun)}for(const xx of [-14,-2,10]){const line=new THREE.Mesh(new THREE.BoxGeometry(9,.03,.13),new THREE.MeshBasicMaterial({color:0xe8e3c7}));line.position.set(xx,3.76,0);g.add(line)}g.position.set(x,0,z);scene.add(g);return g}
function createEscort(scene,x,z,s){const g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:0x354247,roughness:.7,metalness:.18});const h=new THREE.Mesh(new THREE.BoxGeometry(13*s,1.8*s,3.4*s),m);h.position.y=.7*s;g.add(h);const c=new THREE.Mesh(new THREE.BoxGeometry(3*s,2.2*s,2.2*s),m);c.position.set(1.2*s,2.4*s,0);g.add(c);g.position.set(x,0,z);scene.add(g)}
